In [5]:
#cleaning
import pandas as pd
import numpy as np
pd.options.display.max_rows = 999

# Collection

In [6]:
df = pd.read_csv('../datasets/exoplanet_raw.csv', header = 47) #header param necessary to remove empty space
df.head()

,pl_name,hostname,disc_facility,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,...,pl_orbeccenlim,pl_insol,pl_insolerr1,pl_insolerr2,pl_insollim,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtlim,ttv_flag
0,11 Com b,11 Com,Xinglong Station,326.03000,0.32,-0.32,0.0,1.29,0.05,-0.05,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,11 UMi b,11 UMi,Thueringer Landessternwarte Tautenburg,516.21997,3.20,-3.20,0.0,1.53,0.07,-0.07,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,14 And b,14 And,Okayama Astrophysical Observatory,185.84000,0.23,-0.23,0.0,0.83,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,14 Her b,14 Her,W. M. Keck Observatory,1773.40002,2.50,-2.50,0.0,2.93,0.08,-0.08,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,16 Cyg B b,16 Cyg B,Multiple Observatories,798.50000,1.00,-1.00,0.0,1.66,0.03,-0.03,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

 Dictionary found here:
 https://exoplanetarchive.ipac.caltech.edu/docs/API_PS_columns.html

In [7]:
df.shape

(4364, 41)

In [8]:
df.describe()

,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxlim,pl_rade,pl_radeerr1,...,pl_orbeccenlim,pl_insol,pl_insolerr1,pl_insolerr2,pl_insollim,pl_eqt,pl_eqterr1,pl_eqterr2,pl_eqtlim,ttv_flag
count,4.224000e+03,4.045000e+03,4.045000e+03,4224.000000,4220.000000,1971.000000,1970.000000,4220.000000,4350.000000,3291.000000,...,3885.000000,2784.000000,2701.000000,2701.000000,2720.0,3258.000000,950.000000,950.000000,3244.000000,4364.000000
mean,2.051440e+03,9.415575e+02,-9.265116e+02,-0.000473,5.434472,0.364280,-0.341219,-0.000474,5.661936,0.596483,...,0.037838,361.221114,41.668663,-34.127679,0.0,919.308778,40.708421,-39.163158,0.000617,0.073327
std,1.123605e+05,5.739126e+04,5.739023e+04,0.037690,92.293220,5.095575,5.088378,0.021767,5.388018,1.732462,...,0.202608,1243.582734,254.652466,222.261616,0.0,463.289171,67.837749,67.827213,0.024826,0.260703
min,9.070629e-02,0.000000e+00,-3.650000e+06,-1.000000,0.004400,0.000000,-200.000000,-1.000000,0.296000,0.000000,...,-1.000000,0.060000,0.000000,-7200.000000,0.0,50.000000,1.000000,-1217.000000,0.000000,0.000000
25%,4.465547e+00,1.600000e-05,-1.350000e-03,0.000000,0.053000,0.000800,-0.030000,0.000000,1.746250,0.140000,...,0.000000,21.495000,1.300000,-18.230000,0.0,569.250000,14.000000,-42.000000,0.000000,0.000000
50%,1.174096e+01,1.000000e-04,-1.000000e-04,0.000000,0.101600,0.002600,-0.002500,0.000000,2.720000,0.310000,...,0.000000,83.045000,5.240000,-4.750000,0.0,826.500000,25.000000,-24.000000,0.000000,0.000000
75%,4.148466e+01,1.300000e-03,-1.600000e-05,0.000000,0.263200,0.030000,-0.000800,0.000000,11.814000,0.645000,...,0.000000,285.737500,20.480000,-1.190000,0.0,1163.750000,47.000000,-14.000000,0.000000,0.000000
max,7.300000e+06,3.650000e+06,0.000000e+00,1.000000,3500.000000,200.000000,0.600000,0.000000,77.342000,68.910000,...,1.000000,44900.000000,8100.000000,0.000000,0.0,4050.000000,1217.000000,-1.000000,1.000000,1.000000

In [9]:
df.isna().sum()

pl_name               0
hostname              0
disc_facility         0
pl_orbper           140
pl_orbpererr1       319
pl_orbpererr2       319
pl_orbperlim        140
pl_orbsmax          144
pl_orbsmaxerr1     2393
pl_orbsmaxerr2     2394
pl_orbsmaxlim       144
pl_rade              14
pl_radeerr1        1073
pl_radeerr2        1073
pl_radelim           14
pl_radj              16
pl_radjerr1        1075
pl_radjerr2        1075
pl_radjlim           16
pl_bmasse            22
pl_bmasseerr1      2565
pl_bmasseerr2      2565
pl_bmasselim         22
pl_bmassj            22
pl_bmassjerr1      2565
pl_bmassjerr2      2565
pl_bmassjlim         22
pl_bmassprov          0
pl_orbeccen         479
pl_orbeccenerr1    3165
pl_orbeccenerr2    3165
pl_orbeccenlim      479
pl_insol           1580
pl_insolerr1       1663
pl_insolerr2       1663
pl_insollim        1644
pl_eqt             1106
pl_eqterr1         3414
pl_eqterr2         3414
pl_eqtlim          1120
ttv_flag              0
dtype: int64

# Cleaning Nulls

In [10]:

df = df.dropna(axis = 1, thresh = 2176) #thresh parameter keeps any column with less than half the necessary data

This drops 10 columns from our dataframe.  Not a terrible loss!  
From here we can imput our data better.

In [11]:
df.isna().sum()

pl_name              0
hostname             0
disc_facility        0
pl_orbper          140
pl_orbpererr1      319
pl_orbpererr2      319
pl_orbperlim       140
pl_orbsmax         144
pl_orbsmaxlim      144
pl_rade             14
pl_radeerr1       1073
pl_radeerr2       1073
pl_radelim          14
pl_radj             16
pl_radjerr1       1075
pl_radjerr2       1075
pl_radjlim          16
pl_bmasse           22
pl_bmasselim        22
pl_bmassj           22
pl_bmassjlim        22
pl_bmassprov         0
pl_orbeccen        479
pl_orbeccenlim     479
pl_insol          1580
pl_insolerr1      1663
pl_insolerr2      1663
pl_insollim       1644
pl_eqt            1106
pl_eqtlim         1120
ttv_flag             0
dtype: int64

I want a more thorough null-imputation method, so I'll backfill values up to a limit of 25 values, and then fill with the median otherwise.

In [12]:
df = df.fillna(method = 'bfill', limit =25) #limit of 25 makes sure the backfill doesn't run forever
df = df.fillna(value = df.median()) #median value is less susceptible to being pulled by high outliers

In [13]:
df.isna().sum()

pl_name           0
hostname          0
disc_facility     0
pl_orbper         0
pl_orbpererr1     0
pl_orbpererr2     0
pl_orbperlim      0
pl_orbsmax        0
pl_orbsmaxlim     0
pl_rade           0
pl_radeerr1       0
pl_radeerr2       0
pl_radelim        0
pl_radj           0
pl_radjerr1       0
pl_radjerr2       0
pl_radjlim        0
pl_bmasse         0
pl_bmasselim      0
pl_bmassj         0
pl_bmassjlim      0
pl_bmassprov      0
pl_orbeccen       0
pl_orbeccenlim    0
pl_insol          0
pl_insolerr1      0
pl_insolerr2      0
pl_insollim       0
pl_eqt            0
pl_eqtlim         0
ttv_flag          0
dtype: int64

# Dropping unwanted columns

I don't want the columns outlining the margins of error for each feature, nor do I need the 'controversial' flag.

In [14]:
df = df.drop(columns = ['pl_orbpererr1','pl_orbpererr2','pl_orbperlim','pl_orbsmaxlim','pl_radeerr1','pl_radeerr2',
                  'pl_radelim','pl_radjerr1','pl_radjerr2','pl_radjlim','pl_bmasselim','pl_bmassjlim','pl_bmassprov',
                  'pl_orbeccenlim','pl_insolerr1','pl_insolerr2','pl_insollim','pl_eqtlim','ttv_flag'])

In [15]:
df.isna().sum()

pl_name          0
hostname         0
disc_facility    0
pl_orbper        0
pl_orbsmax       0
pl_rade          0
pl_radj          0
pl_bmasse        0
pl_bmassj        0
pl_orbeccen      0
pl_insol         0
pl_eqt           0
dtype: int64

In [17]:
df.to_csv('../datasets/backfill_median_data.csv', index = False)